#!/bin/bash

# Any copyright is dedicated to the Public Domain.
# http://creativecommons.org/publicdomain/zero/1.0/

set -eEu -o pipefail
shopt -s extdebug
IFS=$'\n\t'
trap 'onFailure $?' ERR

function onFailure() {
  echo "Unhandled script error $1 at ${BASH_SOURCE[0]}:${BASH_LINENO[0]}" >&2
  exit 1
}

echo "Setting up..."

echo -en "Installing noderify..."
if ! command -v noderify &> /dev/null
then
  npm install -g noderify
fi

echo -en "Minifying with noderify..."
cd apps/mobile/nodejs-assets/nodejs-project
yarn install
# node ./scripts/build.js
noderify main.js --ignoreMissing > _main.js
rm main.js
mv _main.js main.js

echo
echo -en "Remove sodium-native"
find ./node_modules -name sodium-native -type d -print0 | xargs -0 rm -r --

cd ../..
echo -en " done.\n"

